services:
  guard:
    build: .
    container_name: server_guard_bot
    restart: unless-stopped
    ports:
      - "127.0.0.1:9999:9999/udp"
      - "127.0.0.1:8080:8080/tcp"
    volumes:
      - ../data:/data
    env_file:
      - ../.env
    environment:
      - PYTHONUNBUFFERED=1
